name: CI

on:
  push: {}
  pull_request:
    types: [opened, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23'

      - uses: actions/checkout@v3
      - name: Pull Postgres
        run: docker pull postgres:14.0
      - name: Pull MariaDB
        run: docker pull mariadb:10.8
      - name: Pull SQLServer
        run: docker pull mcr.microsoft.com/mssql/server:2022-latest
      - name: Check go version
        run: go version
      - name: Run linters
        run: go vet ./... && go install honnef.co/go/tools/cmd/staticcheck@latest && bash -c "$(go env GOPATH)/bin/staticcheck ./..."
      - name: Run Tests
        run: ./scripts/run-all-tests.sh
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.txt,benchmarks/coverage.txt,examples/coverage.txt,adapters/kpgx/coverage.txt,adapters/kpgx5/coverage.txt,adapters/ksqlite3/coverage.txt,adapters/modernc-ksqlite/coverage.txt,adapters/kpostgres/coverage.txt,adapters/kmysql/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}


